### PR TITLE
Support installing additional packages

### PR DESCRIPTION
**Pull request by hennr**
Hi @SanderKnape,

we make use of your github-runner and were in need of some additional debian packages in our case.
This PR adds support for installing debian packages when running the container by an environment variable.

If you have anything that we should change before merging, please let us know.

Cheers from Berlin

### CODE REVIEW

**Comment by SanderKnape** [comment]
Hi @hennr , thanks for your PR! Out of curiosity: is it not easier to build a new image from this image?

**Comment by hennr** [comment]
Hi there, glad you answered that fast!

Yes, it is easier building a new image based on this and that's what we are doing at the moment.
While reviewing our approach we thought about the downsides of this approach: Another layer of abstraction, the need to push our own image to a registry, keeping track of changes you may make on the base image.
Then we decided to bring this upstream, it may help someone else and gives something back that may be handy for you as well.
It's what free software is about, isn't it?

**Comment by hennr** [comment]
Being curious as well I have to ask if you have any other thoughts about this PR @SanderKnape?

**Comment by SanderKnape** [comment]
Thanks for the contribution!

**Pull request merged**
